export const LIMITS = {
  GET_COMMENTS: 4,
  GET_REPLIES: 4,
  GET_POSTS: 10,
  GET_USER_BOOKMARKED_POSTS: 12,
  GET_NOTIFICATIONS: 10,
  GET_MESSAGES: 50,
  GET_CONVERSATIONS: 10,
  GET_USERS_BY_USERNAME: 5,
} as const;
